### ISSUE TITLE
[Bug] 204 MOTD 顏色 BUG

### ISSUE THREAD

**Issue by haer0248** [haer0248/mclist-xyz#1]
![image](https://user-images.githubusercontent.com/25150003/91633329-f7299180-ea19-11ea-88f4-4f975717f230.png)
![image](https://user-images.githubusercontent.com/25150003/91633331-fabd1880-ea19-11ea-8e38-5b3f6a588b9d.png)

**Comment by haer0248** [comment]
ID 101、94 也出現相同問題

**Comment by TheLishiba7** [comment]
Fix and tested above MOTD issue. 
This issue was causing by formatting codes will reset previous color codes.
